### ISSUE TITLE
proxy IP异常

### ISSUE THREAD

**Issue by justlagom** [JustLagom/Trojan-and-TrojanSub#1]
clash meta for Android/gui for clash均无法正常读取path路径中proxy IP以访问cf站点；
xray系v2rayN/v2rayNG均正常
（仅目前测试）

**Comment by EVA0M3** [comment]
也遇到此问题 无法正常访问cf托管的网站 望大佬解决 感谢

**Comment by justlagom** [comment]
> 也遇到此问题 无法正常访问cf托管的网站 望大佬解决 感谢
TrojanSub订阅器和_worker.js脚本代码已更新，可以自行测试🥰 please Thanks
